# General configuration for Spring Boot application
server.port=8090
spring.application.name=db-insert-data-app

spring.datasource.url=jdbc:postgresql://localhost:5432/insert_data
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.data-source-properties.reWriteBatchedInserts=true
# JDBC max retries
jdbc.max-retries=5

# Workers for each list is the number of threads that will be created to take records from Redis
configuration.cdr-workers=5
# Batch size for each list of workers
# quantity of records that will be taken from Redis and inserted into the database every schedule
configuration.cdr-batch-size=15000
# Interval in milliseconds for each list of workers
configuration.interval-millis=1000

# Mode -> logs|database|logs_database default is logs
application.mode=logs_database
application.cdr.separator=|
# Message length configuration for CDRs
# -1: Store complete message text
# 0: Do not store message text at all
# Positive value: Store specified number of characters
application.cdr.message-length=-1

# Flyway
# Is used to create the tables in the database the first time the application is executed
spring.flyway.enabled=true
spring.flyway.table=_flyway_history
spring.flyway.clean-disabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.clean-on-validation-error=false

# Threads
spring.threads.virtual.enabled=true

# Disable DataSourceAutoConfiguration
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.listener.concurrency=3