CREATE TABLE IF NOT EXISTS cdr (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.cdr_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
        CYCLE
    ),
    record_date                TIMESTAMP NOT NULL,
    submit_date                TIMESTAMP,
    delivery_date              TIMESTAMP,
    message_type               VARCHAR(10),
    message_id                 VARCHAR(50),
    origination_protocol       VARCHAR(20),
    origination_network_id     VARCHAR(20),
    origination_type           VARCHAR(5),
    destination_type           VARCHAR(20),
    destination_protocol       VARCHAR(20),
    destination_network_id     VARCHAR(20),
    routing_id                 INT,
    status                     VARCHAR(50),
    status_code                VARCHAR(50),
    comment                    VARCHAR(50),
    dialog_duration            BIGINT,
    processing_time            BIGINT,
    data_coding                INT,
    validity_period            VARCHAR(50),
    addr_src_digits            VARCHAR(50),
    addr_src_ton               INT,
    addr_src_npi               INT,
    addr_dst_digits            VARCHAR(50),
    addr_dst_ton               INT,
    addr_dst_npi               INT,
    remote_dialog_id           BIGINT,
    local_dialog_id            BIGINT,
    local_spc                  INT,
    local_ssn                  INT,
    local_global_title_digits  VARCHAR(255),
    remote_spc                 INT,
    remote_ssn                 INT,
    remote_global_title_digits VARCHAR(50),
    imsi                       VARCHAR(50),
    nnn_digits                 VARCHAR(50),
    originator_sccp_address    VARCHAR(50),
    mt_service_center_address  VARCHAR(50),
    message                    TEXT,
    esm_class                  VARCHAR(20),
    udhi                       VARCHAR(20),
    registered_delivery        INT,
    msg_reference_number       VARCHAR(20),
    total_segment              INT,
    segment_sequence           INT,
    retry_number               INT,
    parent_id                  VARCHAR(50),
    broadcast_id               INT,
    PRIMARY KEY (id, record_date)
) PARTITION BY RANGE (record_date);

CREATE TABLE cdr_2025_09 PARTITION OF cdr
    FOR VALUES FROM ('2025-08-25') TO ('2025-10-01');

CREATE INDEX IF NOT EXISTS idx_cdr_message_type ON cdr (message_type);
CREATE INDEX IF NOT EXISTS idx_cdr_status ON cdr (status);
CREATE INDEX IF NOT EXISTS idx_cdr_origination_type ON cdr (origination_type);
CREATE INDEX IF NOT EXISTS idx_cdr_origination_protocol ON cdr (origination_protocol);
CREATE INDEX IF NOT EXISTS idx_cdr_destination_protocol ON cdr (destination_protocol);
CREATE INDEX IF NOT EXISTS idx_cdr_destination_type ON cdr (destination_type);
CREATE INDEX IF NOT EXISTS idx_cdr_addr_src_digits ON cdr (addr_src_digits);
CREATE INDEX IF NOT EXISTS idx_cdr_addr_dst_digits ON cdr (addr_dst_digits);
CREATE INDEX IF NOT EXISTS idx_cdr_origination_network_id ON cdr (origination_network_id);
CREATE INDEX IF NOT EXISTS idx_cdr_destination_network_id ON cdr (destination_network_id);
CREATE INDEX IF NOT EXISTS idx_cdr_registered_delivery ON cdr (registered_delivery);
CREATE INDEX IF NOT EXISTS idx_cdr_broadcast_id ON cdr (broadcast_id);